version: 2
jobs:
  build_clang_latest:
    environment:
      IMAGE_NAME: asarium/fso_compile
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest images/compile_clang_latest

  build_gcc_latest:
    environment:
      IMAGE_NAME: asarium/fso_compile
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest images/compile_gcc_latest

  build_gcc_lowest:
    environment:
      IMAGE_NAME: asarium/fso_compile
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest images/compile_gcc_lowest

workflows:
  version: 2
  build-images:
    jobs:
      - build_clang_latest:
          filters:
            branches:
              only: master
      - build_gcc_latest:
          filters:
            branches:
              only: master
      - build_gcc_lowest:
          filters:
            branches:
              only: master