version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: asarium/fso_compile
    docker:
      - image: circleci/buildpack-deps:stretch

references:
  build_steps: &build_steps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:clang-latest images/compile_clang_latest
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish_steps: &publish_steps
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:clang_latest

jobs:
  build_clang_latest:
    executor: docker-publisher
    environment:
      TAG_NAME: clang-latest
    <<: *build_steps

  publish_clang_latest:
    executor: docker-publisher
    environment:
      TAG_NAME: clang-latest
    <<: *publish_steps

workflows:
  version: 2
  build-images:
    jobs:
      - build_clang_latest
      - publish_clang_latest:
          requires:
            - build_clang_latest